apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: {{ .Values.name }}-{{ .Values.app_group }}-{{ .Values.tag_name }}
    app-group: {{ .Values.app_group }}
    template: {{ .Values.name }}-deploy
  name: {{ .Values.name }}-{{ .Values.app_group }}-{{ .Values.tag_name }}
spec:
  ports:
  - name: 3000-tcp
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    deploymentconfig: {{ .Values.name }}-{{ .Values.app_group }}-{{ .Values.tag_name }}
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
